CLIENT_AUTH = False
CLIENT_IP = "127.0.0.1"
CLIENT_PORT = "6800"
CLIENT_USERNAME = ""
CLIENT_PWD = ""

MONGODB_HOST = '127.0.0.1'
MONGODB_PORT = 27017
MONGODB_COLLECTION = "BaiDuSearch"
MONGODB_NAMESPACE = "bd_search"

SPIDER_SCRAPYD_NAME = "BaiDuSearch"

SERVER_IP = "0.0.0.0"
SERVER_PORT = 9000
